# -*- Tcl -*-
# $Id: de.msg 339 2007-02-04 15:24:59Z tlu $
# --- new translations
::msgcat::mcset de \
"Are you sure to install the DVI previer - dviout?"\
"Sind Sie sicher, daß Sie den DVI Betrachter dviout installieren wollen?"
::msgcat::mcset de \
"TeX Live has not been successfully installed" \
"TeX Live wurde auf Ihrem System nicht erfolgreich installiert"
::msgcat::mcset de \
"A problem copying files by tlpm" \
"Problem beim Dateikopieren mit tlpm"
::msgcat::mcset de \
"\n\nMost importantly, %s should be added to your PATH for the current and future sessions.

Formats will be built for each user when needed. If you wish to build all formats at once, for all users of your system, run fmtutil-sys --all.

For future global configuration changes, edit the files in %s (or run texconfig or texconfig-sys).

tlpmgui can be run again to add or remove individual packages or collections.

The TeX Live web site (http://tug.org/texlive/) contains updates and corrections.

Welcome to TeX Live!"\
"\n\nWichtig: Fügen Sie für diese und zukünftige Anwendungen %s Ihrer Umgebungsvariablen PATH hinzu.

Formate werden für jeden Benutzer nach Bedarf erzeugt. Falls Sie alle Formate für Jeden auf einmal erzeugen wollen, rufen Sie fmtutil-sys --all auf.

Zur globalen Konfiguration editieren Sie die Dateien in %s (oder rufen Sie texconfig oder texconfig-sys auf).

Sie können tlpmgui erneut aufrufen, um einzelne Pakete oder Kollektionen hinzuzufügen oder zu löschen.

Die TeX Live Web Site (http://tug.org/texlive/) enthält Updates und Korrekturen.

Willkommen zu TeX Live!"
::msgcat::mcset de \
"Installation is finished" \
"Installation beendet"
::msgcat::mcset de \
"\nYou should add %s to your PATH environment variable"\
"\nSie sollten %s Ihrer Umgebungsvariablen PATH hinzufügen"
::msgcat::mcset de \
"Perl installation"\
"Installation von Perl"
::msgcat::mcset de \
"Are you sure to install perl?"\
"Wollen Sie Perl wirklich installieren?"
::msgcat::mcset de \
"Warning! Perl is already installed in your system!"\
"Warnung! Perl ist auf Ihrem System bereits installiert!"
::msgcat::mcset de \
"Perl is not installed in your system, but is necessary for complete installation of TeX Live"\
"Perl ist auf Ihrem System noch nicht installiert, ist aber für eine vollständige TeX Live Installation erforderlich"
::msgcat::mcset de \
"Ghostscript installation"\
"Installation von Ghostscript"
::msgcat::mcset de \
"Are you sure to install Ghostscript?"\
"Wollen Sie Ghostscript wirklich installieren?"
::msgcat::mcset de \
"Warning! Ghostscript is already installed in your system!\nPath: %s" \
"Warning! Ghostscript ist auf Ihrem System bereits installiert!\nPfad: %s"
::msgcat::mcset de \
"Ghostscript is not installed in your system, but is necessary for correct work of TeX Live" \
"Ghostscript ist auf Ihrem System noch nicht installiert, ist aber für eine vollständige TeX Live Installation erforderlich"

# ---
::msgcat::mcset de "Setting RW attributes ..." "Setzen der RW Attribute ..."
::msgcat::mcset de "Searching for packages ..." "Durchsuchen von Paketen ..."
::msgcat::mcset de "Preinstall actions" "Aktionen vor Installation"
::msgcat::mcset de "Postinstall actions ..." "Aktionen nach Installation ..."
::msgcat::mcset de "Copying files ..." "Kopieren von Dateien ..."
::msgcat::mcset de "Installing packages ..." "Installation von Paketen ..."
::msgcat::mcset de "Removing packages ..." "Entfernen von Paketen ..."
::msgcat::mcset de "Removing files ..."  "Entfernen von Dateien ..."
::msgcat::mcset de "Refreshing the database ..." "Auffrischen der Datenbasis ..."
::msgcat::mcset de "Next" "Weiter"
::msgcat::mcset de "yes" "Ja"
::msgcat::mcset de "no" "Nein"

# guinb1.tcl
::msgcat::mcset de\
"\"%s\" not found."\
"\"%s\" nicht gefunden."

::msgcat::mcset de\
"tlpm is needed for installing TeX Live and adding/removing packages"\
"tlpm ist erforderlich, um TeX Live zu installieren oder Pakete hinzuzufügen oder zu entfernen."

::msgcat::mcset sk\
"\"Temp\" directory is needed for installing TeX Live and adding/removing packages"\
"\"Temp\" Folder ist erforderlich, um TeX Live zu installieren oder Pakete hinzuzufügen oder zu entfernen."

::msgcat::mcset de\
"File writing failed!"\
"Fehler beim Schreiben der Datei!"

::msgcat::mcset de\
"Writing of the %s file failed!\nCheck the file permissions."\
"Fehler beim Schreiben der Datei %s!\nÜberprüfen Sie die Schreibrechte."

::msgcat::mcset de\
"File reading failed!"\
"Fehler beim Lesen der Datei!"

::msgcat::mcset de\
"Read of the %s  file failed!\nCheck the file permissions and whether it exist."\
"Fehler beim Lesen der Datei %s!\nÜberprüfen Sie die Leserechte bzw. ob die Datei überhaupt existiert."

::msgcat::mcset de "Warning" "Warnung"

::msgcat::mcset de\
"Environment variable \"%s\" exists.\nAre you sure to replace?"\
"Umgebungsvariable \"%s\" existiert.\nWollen Sie diese wirklich überschreiben?"

::msgcat::mcset de\
"Current value:\n%s=%s"\
"Aktueller Wert:\n%s=%s"

# tooltips
::msgcat::mcset de\
"Enter starting chars of the package name to speed-up the search"\
"Benutzen Sie die Tastatur um ein Paket schnell zu finden"

::msgcat::mcset de\
"Selects the path/drive with TeX Live %s"\
"Wählen Sie Laufwerk und Pfad für TeX Live %s aus"

::msgcat::mcset de\
"Selects the destination directory of the TeX Live installation"\
"Wählen Sie das Installationsziel für TeX Live aus"

::msgcat::mcset de\
"Not ready yet"\
"Noch nicht fertig"

::msgcat::mcset de\
"Searches for installed packages"\
"Suchen installierter Pakete"

::msgcat::mcset de\
"Removes selected packages"\
"Entfernen ausgewählter Pakete"

::msgcat::mcset de\
"Info on the selected package"\
"Info über ausgewählte Pakete"

::msgcat::mcset de\
"Searches for not installed packages"\
"Suchen nicht installierter Pakete"

::msgcat::mcset de\
"Installs selected packages"\
"Installieren ausgewählter Pakete"

#
::msgcat::mcset de\
"Collections:"\
"Kollektionen:"

::msgcat::mcset de\
"Confirm to install"\
"Installation bestätigen"

::msgcat::mcset de\
"Are you sure to install TeX Live?"\
"Wollen Sie die TeX Live Installation wirklich starten?"

::msgcat::mcset de\
"Remove the texmf-local directory"\
"Entfernen des texmf-local Verzeichnisses"

#-- new since 1.0
::msgcat::mcset de\
"Install for all users\n(administrator privileges required)"\
"Installation für alle Benutzer\n(Administrator-Rechte erforderlich)"

::msgcat::mcset de\
"Run from DVD"\
"Von DVD ausführen"

::msgcat::mcset de\
"Setting environment variables for running from DVD"\
"Umgebung für Ausführen von DVD setzen"

::msgcat::mcset de\
"Setting the environment"\
"Umgebungvariablen setzen"

::msgcat::mcset de\
"Set"\
"Setzen"

::msgcat::mcset de\
"TeX Live is ready to run directly from the DVD"\
"TeX Live ist direkt von der DVD ausführbar"

#----------
#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/displaylog.tcl:5
::msgcat::mcset de\
"Contents of %s"\
"Inhalt von %s"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/displaylog.tcl:11
::msgcat::mcset de\
"Contents of the %s file:"\
"Inhaltsdatei: %s"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/displaylog.tcl:27
::msgcat::mcset de\
"Close"\
"Schließen"

#. widget: window title
#: D:/Work/TclTk/TL/tl43.vfs/gui.tcl:13
::msgcat::mcset de\
"TeX Live installation and maintenance utility, %s"\
"TeX Live Installations- und Wartungsprogramm, %s"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/gui.tcl:32
::msgcat::mcset de\
"Installation"\
"Installation"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/gui.tcl:43
#: D:/Work/TclTk/TL/tl43.vfs/guinb3.tcl:11
#: D:/Work/TclTk/TL/tl43.vfs/guinb3.tcl:82
#: D:/Work/TclTk/TL/tl43.vfs/guinb3.tcl:87
#: D:/Work/TclTk/TL/tl43.vfs/guinb3.tcl:131
::msgcat::mcset de\
"Removing packages"\
"Pakete entfernen"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/gui.tcl:47
::msgcat::mcset de\
"Manage the installation"\
"Installation bearbeiten"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/gui.tcl:51
::msgcat::mcset de\
"Removing the installation"\
"Installation entfernen"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/gui.tcl:68
::msgcat::mcset de\
"Help"\
"Hilfe"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/gui.tcl:72
::msgcat::mcset de\
"Exit"\
"Ende"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb1.tcl:9
::msgcat::mcset de\
"Installation of the TeX Live %s edition"\
"Installation der TeX Live %s Distribution"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb1.tcl:15
::msgcat::mcset de\
"Main customization"\
"Anpassung"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb1.tcl:19
#: D:/Work/TclTk/TL/tl43.vfs/guinb1col.tcl:3
::msgcat::mcset de\
"Standard collections"\
"Standard-Kollektionen"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb1.tcl:20
#: D:/Work/TclTk/TL/tl43.vfs/guinb1.tcl:23
::msgcat::mcset de\
"Select"\
"Auswählen"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb1.tcl:22
#: D:/Work/TclTk/TL/tl43.vfs/guinb1lang.tcl:3
::msgcat::mcset de\
"Language collections"\
"Sprach-Kollektionen"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb1.tcl:29
#: D:/Work/TclTk/TL/tl43.vfs/guinb1.tcl:33
#: D:/Work/TclTk/TL/tl43.vfs/guinb2.tcl:120
::msgcat::mcset de\
"Install"\
"Installieren"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb1.tcl:47
::msgcat::mcset de\
"Select a scheme"\
"Schema auswählen"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb1.tcl:58
::msgcat::mcset de\
"Select a system"\
"System auswählen"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb1.tcl:91
::msgcat::mcset de\
"Directories"\
"Verzeichnisse"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb1.tcl:126
::msgcat::mcset de\
"Options"\
"Optionen"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb1.tcl:130
::msgcat::mcset de\
"alternative directory for generated fonts"\
"erzeugte Fonts in Alternativ-Verzeichnis kopieren"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb1.tcl:131
::msgcat::mcset de\
"create symlinks in standard directories"\
"symbolische Links in Standardverzeichnissen anlegen"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb1.tcl:132
::msgcat::mcset de\
"do not install the macro/font doc tree"\
"den Makro/Font Dokumentationsbaum nicht installieren"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb1.tcl:133
::msgcat::mcset de\
"do not install the macro/font source tree"\
"den Makro/Font Quellbaum nicht installieren"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb2.tcl:12
#: D:/Work/TclTk/TL/tl43.vfs/guinb3.tcl:12
::msgcat::mcset de\
"Use Ctrl or Shift or drag to select more"\
"Auswahl mehrerer Pakete: Linke Maustaste gedrückt halten, oder Mausklick bei gedrückter Strg oder Shift Taste"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb2.tcl:18
::msgcat::mcset de\
"Select packages to install"\
"Auswahl der zu installierenden Pakete"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb2.tcl:35
#: D:/Work/TclTk/TL/tl43.vfs/guinb3.tcl:35
::msgcat::mcset de\
"Buttons"\
"Funktion"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/gluelanguage.tcl:24
#: D:/Work/TclTk/TL/tl43.vfs/gui.tcl:95
#: D:/Work/TclTk/TL/tl43.vfs/guinb1.tcl:37
#: D:/Work/TclTk/TL/tl43.vfs/guinb2.tcl:115
#: D:/Work/TclTk/TL/tl43.vfs/proc.tcl:64
#: D:/Work/TclTk/TL/tl43.vfs/proc.tcl:95
#: D:/Work/TclTk/TL/tl43.vfs/proc.tcl:107
#: D:/Work/TclTk/TL/tl43.vfs/proc.tcl:126
::msgcat::mcset de\
"Error"\
"Fehler"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/gui.tcl:39
#: D:/Work/TclTk/TL/tl43.vfs/guinb2.tcl:11
#: D:/Work/TclTk/TL/tl43.vfs/guinb2.tcl:126
#: D:/Work/TclTk/TL/tl43.vfs/guinb2.tcl:131
#: D:/Work/TclTk/TL/tl43.vfs/guinb2.tcl:185
::msgcat::mcset de\
"Adding packages"\
"Pakete hinzufügen"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb2.tcl:214
::msgcat::mcset de\
"Packages installed successfully." \
"Pakete erfolgreich installiert."

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb2.tcl:214
::msgcat::mcset de\
"Please go to \"Manage the installation\" and edit fmtutil.cfg or updmap.cfg if you have added a format or font package." \
"Bitte wählen Sie \"Installation bearbeiten\" und editieren fmtutil.cfg oder updmap.cfg, falls Sie ein Format- oder Fontpaket hinzugefügt haben."

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb2.tcl:179
#: D:/Work/TclTk/TL/tl43.vfs/guinb3.tcl:125
#: D:/Work/TclTk/TL/tl43.vfs/searchscheme.tcl:24
::msgcat::mcset de\
"Info"\
"Info"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb2.tcl:213
#: D:/Work/TclTk/TL/tl43.vfs/guinb3.tcl:144
::msgcat::mcset de\
"Info on the selected item"\
"Info zu ausgewählten Paketen"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb2.tcl:219
::msgcat::mcset de\
"\nAttention. Please check if a CD drive with the TeX Live CD\n is properly selected.\n\nFirst fill in the list using the \"Search\" button, then select an item and click the \"Install\" or \"Info\" button."\
"\nAchtung. Bitte überprüfen Sie, ob das CD-Laufwerk mit der TeX Live Distribution ordnungsgemäß ausgewählt wurde.\n\nFüllen Sie zunächst die Liste durch Klicken auf den \"Suchen\" Knopf, wählen Sie dann ein oder mehrere Pakete aus und klicken auf den \"Installieren\" Knopf.\n\nInformationen zu einzelnen Paketen erhalten Sie durch Klicken auf den \"Info\" Knopf."

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb3.tcl:19
::msgcat::mcset de\
"Select packages for removal"\
"Auswahl der zu entfernenden Pakete"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb2.tcl:42
#: D:/Work/TclTk/TL/tl43.vfs/guinb3.tcl:39
::msgcat::mcset de\
"Search"\
"Suchen"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb3.tcl:119
::msgcat::mcset de\
"Packages removed successfully"\
"Pakete erfolgreich entfernt"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb3.tcl:150
::msgcat::mcset de\
"\nAttention: to display package information, the CD drive with the TeX Live CD should be selected in the \"Add packages\" tab.\n\nFirst fill in the list using the \"Search\" button, then select an item and click the \"Remove\" button to remove the package."\
"\nAchtung: Für Informationen über die Pakete sollte ein CD Laufwerk mit der TeX Live CD im \"Pakete hinzufügen\" Feld ausgewählt sein.\n\nFüllen Sie zunächst die Liste durch Klicken auf den \"Suchen\" Knopf, wählen Sie dann ein oder mehrere Pakete aus und klicken auf den \"Entfernen\" Knopf.\n\nInformationen zu einzelnen Paketen erhalten Sie durch Klicken auf den \"Info\" Knopf."

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb4.tcl:11
::msgcat::mcset de\
"Manage the existing TeX Live installation"\
"Bearbeiten der bestehenden TeX Live Installation"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb4.tcl:20
::msgcat::mcset de\
"Refresh the ls-R database"\
"Auffrischen der ls-R Datenbasis"

#. widget: unknown
#: D:/Work/TclTk/TL/tl43.vfs/guinb4.tcl:22
::msgcat::mcset de\
"Refresh"\
"Auffrischen"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb1col.tcl:49
#: D:/Work/TclTk/TL/tl43.vfs/guinb1lang.tcl:44
#: D:/Work/TclTk/TL/tl43.vfs/guinb2.tcl:172
#: D:/Work/TclTk/TL/tl43.vfs/guinb4.tcl:28
#: D:/Work/TclTk/TL/tl43.vfs/guinb4.tcl:74
#: D:/Work/TclTk/TL/tl43.vfs/guinb4.tcl:87
#: D:/Work/TclTk/TL/tl43.vfs/guinb4edit.tcl:18
# guinb5.tcl
#: D:/Work/TclTk/TL/tl43.vfs/proc.tcl:68
#: D:/Work/TclTk/TL/tl43.vfs/proc.tcl:80
::msgcat::mcset de\
"Done"\
"Fertig"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb2.tcl:111
#: D:/Work/TclTk/TL/tl43.vfs/guinb3.tcl:72
#: D:/Work/TclTk/TL/tl43.vfs/guinb4.tcl:31
#: D:/Work/TclTk/TL/tl43.vfs/guinb4.tcl:52
#: D:/Work/TclTk/TL/tl43.vfs/guinb4.tcl:56
#: D:/Work/TclTk/TL/tl43.vfs/guinb4.tcl:77
#: D:/Work/TclTk/TL/tl43.vfs/guinb4.tcl:90
#: D:/Work/TclTk/TL/tl43.vfs/guinb4.tcl:112
#: D:/Work/TclTk/TL/tl43.vfs/guinb4.tcl:116
#: D:/Work/TclTk/TL/tl43.vfs/guinb4.tcl:141
#: D:/Work/TclTk/TL/tl43.vfs/guinb4.tcl:145
::msgcat::mcset de\
"Oops"\
"Hoppla"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb4.tcl:39
#: D:/Work/TclTk/TL/tl43.vfs/guinb4.tcl:43
#: D:/Work/TclTk/TL/tl43.vfs/guinb4.tcl:103
#: D:/Work/TclTk/TL/tl43.vfs/guinb4.tcl:132
::msgcat::mcset de\
"Edit language.dat"\
"Editiere language.dat"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb4.tcl:66
::msgcat::mcset de\
"Creating formats"\
"Formate erzeugen"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb4.tcl:68
::msgcat::mcset de\
"All"\
"alle Formate"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb4.tcl:81
::msgcat::mcset de\
"Missing"\
"fehlende Formate"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb4.tcl:100
::msgcat::mcset de\
"Editing fmtutil.cnf"\
"Editiere fmtutil.cnf"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb4.tcl:129
::msgcat::mcset de\
"Editing updmap.cfg"\
"Editiere updmap.cfg"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb4edit.tcl:15
::msgcat::mcset de\
"Cancel"\
"Abbrechen"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb5.tcl:11
#: D:/Work/TclTk/TL/tl43.vfs/guinb5.tcl:18
::msgcat::mcset de\
"Remove the TeX Live installation"\
"Entfernen der TeX Live Installation"

#. widget: unknown
#: D:/Work/TclTk/TL/tl43.vfs/guinb5.tcl:23
::msgcat::mcset de\
"The path to the TL directory: %s"\
"Pfad zum TL Verzeichnis: %s"

#. widget: unknown
#: D:/Work/TclTk/TL/tl43.vfs/guinb3.tcl:76
#: D:/Work/TclTk/TL/tl43.vfs/guinb5.tcl:24
::msgcat::mcset de\
"Remove"\
"Entfernen"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb5.tcl:25
::msgcat::mcset de\
"Confirm removal"\
"Entfernen bestätigen"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb5.tcl:32
::msgcat::mcset de\
"Please wait. Installation removal in progres."\
"Bitte warten. Entfernen der Installation in Arbeit."

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/guinb5.tcl:66
::msgcat::mcset de\
"TeX Live has been sucessfully removed from your system"\
"TeX Live wurde erfolgreich von Ihrem System entfernt."
::msgcat::mcset de "Press \"OK\" to exit" "Drücken Sie \"OK\" zum Beenden."
#. widget: unknown
#: D:/Work/TclTk/TL/tl43.vfs/guinb5.tcl:73
::msgcat::mcset de\
"I can't find the TeX Live directory.\nEnvironment variable TLroot not found."\
"Ich kann das TeX Live Verzeichnis nicht finden.\nUmgebungsvariable TLroot nicht gefunden."

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/searchscheme.tcl:28
::msgcat::mcset de\
"Scheme info"\
"Schema Info"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/wininstall.tcl:69
::msgcat::mcset de\
"Installing TeX Live"\
"Installation von TeX Live"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/wininstall.tcl:73
::msgcat::mcset de\
"Installation in progress. Please wait."\
"Installation in Arbeit. Bitte warten."

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/wininstall.tcl:86
::msgcat::mcset de\
"Wrong path to the TeX Live directory."\
"Falscher Pfad zum TeX Live Verzeichnis."

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/wininstall.tcl:86
::msgcat::mcset de\
"Try again.\nPress the CD/DVD button to select the correct path."\
"Versuchen Sie es noch einmal.\nDrücken Sie den CD/DVD Knopf um den korrekten Pfad auszuwählen."

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/winpostinstall.tcl:92
::msgcat::mcset de\
"TeX Live installed in %s"\
"TeX Live installiert in %s"

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/winpostinstall.tcl:94
::msgcat::mcset de\
"\n\nYou should now reboot your system.\nAfter rebooting you can run tlpmgui to add/remove package(s) or perform other maintenance tasks."\
"\n\nSie sollten Ihr System jetzt neu starten.\nNach dem Neustart können Sie tlpmgui ausführen, um Pakete hinzuzufügen oder zu entfernen, und um Wartung durchzuführen."

#. widget: none
#: D:/Work/TclTk/TL/tl43.vfs/winpostinstall.tcl:96
::msgcat::mcset de\
"\n\nAfter restarting tlpmgui you can add/remove package(s) or perform other maintenance tasks."\
"\n\nNach Neustart von tlpmgui können Sie Pakete hinzufügen oder entfernen, oder Wartung durchführen."

# guinb2.tcl
# guinb3.tcl
::msgcat::mcset de\
"Empty selection!" \
"Leere Auswahl!"

# guinb3.tcl
::msgcat::mcset de\
"Are you sure to remove the selected packages?"\
"Wollen Sie die ausgewählten Pakete wirklich entfernen?"

# guinb2.tcl
::msgcat::mcset de\
"Are you sure to install the selected packages?"\
"Wollen Sie die ausgewählten Pakete wirklich installieren?"

# proc.tcl
::msgcat::mcset de\
"%s\n\nLog written to file %s\nWould you like to read it?"\
"%s\n\nProtokoll geschrieben in die Datei %s\nMöchten Sie die Protokolldatei lesen?"

# guinb5.tcl
::msgcat::mcset de\
"Are you sure to remove your TeX Live installation?"\
"Wollen Sie die TeX Live Installation wirklich entfernen?"

# guinb4.tcl
::msgcat::mcset de\
"Edit"\
"Editieren"

# winpostinstall.tcl
::msgcat::mcset de\
"TeX Live has been sucessfully installed in your system"\
"TeX Live wurde erfolgreich auf Ihrem System installiert."

# gui.tcl:71
::msgcat::mcset de\
"helpen.txt"\
"helpde.txt"

# gui.tcl:71
::msgcat::mcset de\
"helpen"\
"helpde"

# guinb4.tcl
::msgcat::mcset de\
"File \"%s\" not found.\nProbably TeX Live is not correctly installed."\
"Datei \"%s\" nicht gefunden.\nWahrscheinlich wurde TeX Live nicht korrekt installiert."

# guinb4.tcl
::msgcat::mcset de\
"The TEXMFCNF environment variable not found."\
"Variable TEXMFCNF nicht gefunden."

# guinb4.tcl
::msgcat::mcset de\
"Probably TeX Live is not correctly installed."\
"Wahrscheinlich wurde TeX Live nicht korrekt installiert."

# guinb4edit.tcl
::msgcat::mcset de\
"File \"%s\" succesfully saved"\
"Datei \"%s\" erfolgreich gesichert."

# proc.tcl
::msgcat::mcset de\
"Please wait..."\
"Bitte warten..."

# $Id: de.msg 339 2007-02-04 15:24:59Z tlu $
# 2005.10.08 20:10
# 2005.10.11 0:40 TLu - Please wait...
# 2005.10.31 21:55 TLu
