# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded help 1.5 "\
    package require Tcl 8.1;\
    package require Tk 8.1;\
    [list tclPkgSetup $dir help 1.5 {
        {help.tcl source {::help::init ::help::reg ::help::destroy ::help::add_ext}}
        {help_2htm.tcl source {::help::help2html}}
        {help_chk.tcl source {::help::check_refs}}
    }]
"
